# Generated by Django 5.1.3 on 2024-11-08 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import cars.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Марка автомобиля')),
                ('model', models.CharField(max_length=50, verbose_name='Модель автомобиля')),
                ('year', models.PositiveIntegerField(validators=[cars.validators.validate_year], verbose_name='Год выпуска')),
                ('description', models.TextField(verbose_name='Описание автомобиля')),
                ('created_at', models.DateTimeField(verbose_name='Дата и время создания записи')),
                ('updated_at', models.DateTimeField(verbose_name='Дата и время обновления записи')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(verbose_name='Дата и время создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Автомобиль')),
            ],
        ),
    ]
