# Generated by Django 5.1.3 on 2024-11-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_created_at_alter_car_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления записи'),
        ),
    ]
